#!/bin/bash

set -e

ver="14.2.0"
TGT="$(uname -m)-dalix-linux-gnu"

[ -d gcc-$ver ] && rm -rf gcc-$ver
[ -f "gcc-$ver.tar.xz" ] || wget -q --show-progress https://ftp.gnu.org/gnu/gcc/gcc-$ver/gcc-${ver}.tar.xz
[ -f "mpc-1.3.1.tar.gz" ] || wget -q --show-progress https://ftp.gnu.org/gnu/mpc/mpc-1.3.1.tar.gz
[ -f "mpfr-4.2.1.tar.xz" ] || wget -q --show-progress https://ftp.gnu.org/gnu/mpfr/mpfr-4.2.1.tar.xz
[ -f "gmp-6.3.0.tar.xz" ] || wget -q --show-progress https://ftp.gnu.org/gnu/gmp/gmp-6.3.0.tar.xz
tar -xf gcc-$ver.tar.xz

cd gcc-$ver
tar -xf ../mpc-*.tar.gz
tar -xf ../mpfr-*.tar.xz
tar -xf ../gmp-*.tar.xz
mv mpc-* mpc
mv mpfr-* mpfr
mv gmp-* gmp

mkdir build
cd build
../configure \
  --target=$TGT \
  --prefix=$HOME/Opt/Cross/tools \
  --with-glibc-version=2.41 \
  --with-sysroot=$HOME/Opt/Cross/ \
  --with-newlib \
  --without-headers \
  --enable-default-pie \
  --enable-default-ssp \
  --disable-nls \
  --disable-shared \
  --disable-multilib \
  --disable-threads \
  --disable-libatomic \
  --disable-libgomp \
  --disable-libquadmath \
  --disable-libssp \
  --disable-libvtv \
  --disable-libstdcxx \
  --enable-languages=c,c++
make
make install
cd ..
cat gcc/limitx.h gcc/glimits.h gcc/limity.h > \
  $(dirname $($HOME/Opt/Cross/tools/bin/$TGT-gcc -print-libgcc-file-name))/include/limits.h
