#!/bin/bash

pkgname="linux-api-headers"
pkgver="6.13.6"

sources=(
  "https://cdn.kernel.org/pub/linux/kernel/v$(echo -n "$pkgver" | grep -E -o "^[0-9]+").x/linux-$pkgver.tar.xz"
)

USE_HOST_TOOLS=1

function build() {
  mkdir -p $pkgdir/usr
  cd linux-$pkgver
  make mrproper
  make headers
  find usr/include -type f ! -name '*.h' -delete
  cp -rv usr/include $pkgdir/usr
}
