#!/bin/bash

pkgname="coreutils"
pkgver="9.6"

sources=(
	"https://ftp.gnu.org/gnu/coreutils/coreutils-$pkgver.tar.xz"
)

depends=(
	glibc
	libcap
)

makedepends=(
	glibc
	gcc
	binutils
	make
	sed
	gawk
	grep
	diffutils
	libcap
)

function build() {
	cd coreutils-$pkgver
	./configure \
		--prefix=/usr \
		--enable-no-install-program=kill,uptime
	make
	make DESTDIR=$pkgdir install
}
