#!/bin/bash

pkgname="diffutils"
pkgver="3.11"

sources=(
	"https://ftp.gnu.org/gnu/diffutils/diffutils-$pkgver.tar.xz"
)

depends=(
	glibc
)

makedepends=(
	glibc
	gcc
	binutils
	make
	sed
	gawk
	grep
	diffutils
)

function build() {
	cd diffutils-$pkgver
	./configure --prefix=/usr
	make
	make DESTDIR=$pkgdir install
}
