#!/bin/bash

pkgname="expat"
pkgver="2.6.4"

sources=(
	"https://github.com/libexpat/libexpat/releases/download/R_$(echo -n "$pkgver" | tr '.' '_')/expat-$pkgver.tar.xz"
)

depends=(
	glibc
)

makedepends=(
	glibc
	gcc
	binutils
	make
	sed
	gawk
	grep
	diffutils
)

function build() {
	cd expat-$pkgver
	./configure --prefix=/usr \
		--disable-static \
		--docdir=/usr/share/doc/expat-$pkgver
	make
	make DESTDIR=$pkgdir install
	install -m644 doc/*.{html,css} $pkgdir/usr/share/doc/expat-$pkgver
}
