#!/bin/bash

pkgname="flex"
pkgver="2.6.4"

sources=(
  "https://github.com/westes/flex/releases/download/v$pkgver/flex-$pkgver.tar.gz"
)

depends=(
  glibc
)

makedepends=(
  glibc
  gcc
  binutils
  make
  sed
  gawk
  grep
  m4
  diffutils
  texinfo
)

function build() {
  cd flex-$pkgver
  ./configure --prefix=/usr \
    --docdir=/usr/share/doc/flex-$pkgver \
    --disable-static
  make
  make DESTDIR=$pkgdir install
  ln -sv flex $pkgdir/usr/bin/lex
  ln -sv flex.1 $pkgdir/usr/share/man/man1/lex.1
}
