#!/bin/bash

pkgname="gcc"
pkgver="14.2.0"

sources=(
  "https://ftp.gnu.org/gnu/gcc/gcc-$pkgver/gcc-$pkgver.tar.xz"
)

depends=(
  glibc
  gmp
  mpfr
  mpc
  zlib
  binutils
)

makedepends=(
  glibc
  gcc
  binutils
  make
  sed
  gawk
  grep
  gmp
  mpfr
  mpc
  file
  diffutils
  texinfo
  tar
  zlib
)

function build() {
  cd gcc-$pkgver
  case $(uname -m) in
  x86_64)
    sed -e '/m64=/s/lib64/lib/' \
      -i.orig gcc/config/i386/t-linux64
    ;;
  esac
  mkdir build
  cd build
  gcc -dumpmachine
  echo "=========="
  gcc -v
  ../configure --prefix=/usr \
    --build=x86_64-dalix-linux-gnu \
    --host=x86_64-dalix-linux-gnu \
    --target=x86_64-dalix-linux-gnu \
    LD=ld \
    --enable-languages=c,c++ \
    --enable-default-pie \
    --enable-default-ssp \
    --enable-host-pie \
    --disable-multilib \
    --disable-bootstrap \
    --disable-fixincludes \
    --with-system-zlib
  make
  make DESTDIR=$pkgdir install
  mkdir -p $pkgdir/usr/{lib,bin}
  ln -svr /usr/bin/cpp $pkgdir/usr/lib
  mkdir -p $pkgdir/usr/share/man/man1
  ln -sv gcc.1 $pkgdir/usr/share/man/man1/cc.1
  ln -sv gcc $pkgdir/usr/bin/cc
  mkdir -p $pkgdir/usr/lib/bfd-plugins
  ln -sfv ../../libexec/gcc/$(gcc -dumpmachine)/$pkgver/liblto_plugin.so \
    $pkgdir/usr/lib/bfd-plugins/
}
