#!/bin/bash

pkgname="gdbm"
pkgver="1.24"

sources=(
  "https://ftp.gnu.org/gnu/gdbm/gdbm-$pkgver.tar.gz"
)

depends=(
  glibc
)

makedepends=(
  glibc
  gcc
  binutils
  make
  sed
  gawk
  grep
  file
  diffutils
)

function build() {
  cd gdbm-$pkgver
  ./configure --prefix=/usr \
    --disable-static \
    --enable-libgdbm-compat
  make
  make DESTDIR=$pkgdir install
}
