#!/bin/bash

pkgname="gettext"
pkgver="0.24"

sources=(
  "https://ftp.gnu.org/gnu/gettext/gettext-$pkgver.tar.xz"
)

depends=(
  glibc
  acl
)

makedepends=(
  glibc
  gcc
  binutils
  make
  sed
  gawk
  grep
  gzip
  tar
  diffutils
  findutils
  texinfo
  acl
  gettext
)

function build() {
  cd gettext-$pkgver
  am_cv_func_iconv_works="yes" ./configure --prefix=/usr \
    --disable-static \
    --docdir=/usr/share/doc/gettext-$pkgver
  make
  make DESTDIR=$pkgdir install
  chmod -v 0755 $pkgdir/usr/lib/preloadable_libintl.so
}
