#!/bin/bash

pkgname="grep"
pkgver="3.11"

sources=(
  "https://ftp.gnu.org/gnu/grep/grep-$pkgver.tar.xz"
)

depends=(
  glibc
)

makedepends=(
  glibc
  gcc
  binutils
  make
  sed
  gawk
  grep
)

function build() {
  cd grep-$pkgver
  sed -i "s/echo/#echo/" src/egrep.sh
  ./configure --prefix=/usr
  make
  make DESTDIR=$pkgdir install
}
