#!/bin/bash

pkgname="gzip"
pkgver="1.13"

sources=(
	"https://ftp.gnu.org/gnu/gzip/gzip-$pkgver.tar.xz"
)

depends=(
	glibc
)

makedepends=(
	glibc
	gcc
	binutils
	make
	sed
	gawk
	grep
	diffutils
)

function build() {
	cd gzip-$pkgver
	./configure --prefix=/usr
	make
	make DESTDIR=$pkgdir install
}
