#!/bin/bash

pkgname="libxcrypt"
pkgver="4.4.38"

sources=(
  "https://github.com/besser82/libxcrypt/releases/download/v$pkgver/libxcrypt-$pkgver.tar.xz"
)

depends=(
  glibc
)

makedepends=(
  glibc
  gcc
  binutils
  make
  sed
  gawk
  grep
  perl
)

function build() {
  cd libxcrypt-$pkgver
  ./configure --prefix=/usr \
    --enable-hashes=strong,glibc \
    --enable-obsolete-api=no \
    --disable-static \
    --disable-failure-tokens
  make
  make DESTDIR=$pkgdir install
}
