#!/bin/bash

pkgname="m4"
pkgver="1.4.19"

sources=(
  "https://ftp.gnu.org/gnu/m4/m4-$pkgver.tar.xz"
)

depends=(
  glibc
)

makedepends=(
  glibc
  gcc
  binutils
  make
  sed
  gawk
  grep
  diffutils
)

function build() {
  cd m4-$pkgver
  ./configure --prefix=/usr
  make
  make DESTDIR=$pkgdir install
}
