#!/bin/bash

pkgname="make"
pkgver="4.4.1"

sources=(
	"https://ftp.gnu.org/gnu/make/make-$pkgver.tar.gz"
)

depends=(
	glibc
)

makedepends=(
	glibc
	gcc
	binutils
	make
	sed
	gawk
	grep
	diffutils
)

function build() {
	cd make-$pkgver
	./configure --prefix=/usr
	make
	make DESTDIR=$pkgdir install
}
