#!/bin/bash

pkgname="man-pages"
pkgver="6.12"

sources=(
	"https://www.kernel.org/pub/linux/docs/man-pages/man-pages-$pkgver.tar.xz"
)

depends=(
	glibc
)

makedepends=(
	make
	grep
	findutils
	sed
	gcc
)

function build() {
	cd man-pages-$pkgver
	rm -v man3/crypt*
	make -R GIT=false prefix=/usr DESTDIR=$pkgdir install
}
