#!/bin/bash

pkgname="meson"
pkgver="1.7.0"

sources=(
	"https://github.com/mesonbuild/meson/releases/download/$pkgver/meson-$pkgver.tar.gz"
)

depends=(
	glibc
	python
	zlib
)

makedepends=(
	glibc
	gcc
	binutils
	make
	sed
	gawk
	grep
	python
	python-setuptools
)

function build() {
	cd meson-$pkgver
	pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD
	pip3 install --root "$pkgdir" --no-index --find-links dist meson
	install -vDm644 data/shell-completions/bash/meson $pkgdir/usr/share/bash-completion/completions/meson
	install -vDm644 data/shell-completions/zsh/_meson $pkgdir/usr/share/zsh/site-functions/_meson
}
