#!/bin/bash

pkgname="ninja"
pkgver="1.12.1"

sources=(
  "https://github.com/ninja-build/ninja/archive/v$pkgver/ninja-$pkgver.tar.gz"
)

depends=(
  glibc
)

makedepends=(
  glibc
  gcc
  binutils
  make
  sed
  gawk
  grep
  python
)

function build() {
  cd ninja-$pkgver
  python3 configure.py --bootstrap --verbose
  mkdir -p $pkgdir/usr/bin
  mkdir -p $pkgdir/usr/share/{zsh/site-functions,bash-completion/completions}
  install -vm755 ninja $pkgdir/usr/bin/
  install -vDm644 misc/bash-completion $pkgdir/usr/share/bash-completion/completions/ninja
  install -vDm644 misc/zsh-completion $pkgdir/usr/share/zsh/site-functions/_ninja

}
