#!/bin/bash

pkgname="patch"
pkgver="2.7.6"

sources=(
	"https://ftp.gnu.org/gnu/patch/patch-$pkgver.tar.xz"
)

depends=(
	glibc
)

makedepends=(
	glibc
	gcc
	binutils
	make
	sed
	gawk
	grep
	diffutils
)

function build() {
	cd patch-$pkgver
	./configure --prefix=/usr
	make
	make DESTDIR=$pkgdir install
}
