#!/bin/bash

pkgname="perl-xml-parser"
pkgver="2.47"

sources=(
	"https://cpan.metacpan.org/authors/id/T/TO/TODDR/XML-Parser-$pkgver.tar.gz"
)

depends=(
	glibc
	expat
	"perl==$(perl --version | grep -E -o '[0-9]+\.[0-9]+\.[0-9]+' | grep -E -o '^[0-9]+\.[0-9]+')"
)

makedepends=(
	glibc
	gcc
	binutils
	make
	sed
	gawk
	grep
	perl
	expat
)

function build() {
	cd XML-Parser-$pkgver
	perl Makefile.PL INSTALLDIRS=vendor
	make
	make DESTDIR=$pkgdir install
}
