#!/bin/bash

pkgname="pkgconf"
pkgver="2.3.0"

sources=(
	"https://distfiles.ariadne.space/pkgconf/pkgconf-$pkgver.tar.xz"
)

depends=(
	glibc
)

makedepends=(
	glibc
	gcc
	binutils
	make
	sed
	gawk
	grep
	diffutils
	findutils
)

function build() {
	cd pkgconf-$pkgver
	./configure --prefix=/usr \
		--disable-static \
		--docdir=/usr/share/doc/pkgconf-$pkgver
	make
	make DESTDIR=$pkgdir install
	ln -sv pkgconf $pkgdir/usr/bin/pkg-config
	ln -sv pkgconf.1 $pkgdir/usr/share/man/man1/pkg-config.1
}
