#!/bin/bash

pkgname="python-markupsafe"
pkgver="3.0.2"

sources=(
	"https://pypi.org/packages/source/M/MarkupSafe/markupsafe-$pkgver.tar.gz"
)

depends=(
	glibc
	python
)

makedepends=(
	glibc
	gcc
	binutils
	make
	sed
	gawk
	grep
	diffutils
	python
	python-setuptools
)

function build() {
	cd markupsafe-$pkgver
	pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD
	pip3 install --root $pkgdir --no-index --find-links dist Markupsafe
}
