#!/bin/bash

pkgname="python-flit-core"
pkgver="3.11.0"

sources=(
  "https://pypi.org/packages/source/f/flit-core/flit_core-$pkgver.tar.gz"
)

depends=(
  glibc
  python
)

makedepends=(
  glibc
  gcc
  binutils
  make
  sed
  gawk
  grep
  python
)

function build() {
  cd flit_core-$pkgver
  pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD
  pip3 install --root $pkgdir --no-index --find-links dist flit_core
}
