#!/bin/bash

pkgname="python-setuptools"
pkgver="75.8.1"

sources=(
  "https://pypi.org/packages/source/s/setuptools/setuptools-$pkgver.tar.gz"
)

depends=(
  glibc
  python
)

makedepends=(
  glibc
  gcc
  binutils
  make
  sed
  gawk
  grep
  python
)

function build() {
  cd setuptools-$pkgver
  pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD
  pip3 install --root $pkgdir --no-index --find-links dist setuptools
}
