#!/bin/bash

pkgname="python"
pkgver="3.13.2"

sources=(
	"https://www.python.org/ftp/python/$pkgver/Python-$pkgver.tar.xz"
	"https://www.python.org/ftp/python/doc/$pkgver/python-$pkgver-docs-html.tar.bz2"
)

depends=(
	glibc
	expat
	openssl
)

makedepends=(
	glibc
	gcc
	binutils
	make
	sed
	gawk
	grep
	findutils
	expat
	tar
	bzip2
	openssl
)

function build() {
	cd Python-$pkgver
	./configure --prefix=/usr \
		--enable-shared \
		--with-system-expat \
		--enable-optimizations
	make
	make DESTDIR=$pkgdir install
	ln -sfT python3 $pkgdir/usr/bin/python
	install -v -dm755 ${pkgdir}/usr/share/doc/python-${pkgver}/html

	tar --strip-components=1 \
		--no-same-owner \
		--no-same-permissions \
		-C ${pkgdir}/usr/share/doc/python-${pkgver}/html \
		-xvf ../python-${pkgver}-docs-html.tar.bz2
}
