#!/bin/bash

pkgname="python-jinja2"
pkgver="3.1.5"

sources=(
	"https://pypi.org/packages/source/J/Jinja2/jinja2-$pkgver.tar.gz"
)

depends=(
	glibc
	python
	python-markupsafe
)

makedepends=(
	glibc
	gcc
	binutils
	make
	sed
	gawk
	grep
	diffutils
	python
	python-setuptools
	python-flit-core
	python-markupsafe
)

function build() {
	cd jinja2-$pkgver
	pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD
	pip3 install --root $pkgdir --no-index --find-links dist Jinja2
}
