#!/bin/bash

pkgname="sed"
pkgver="4.9"

sources=(
  "https://ftp.gnu.org/gnu/sed/sed-$pkgver.tar.xz"
)

depends=(
  glibc
)

makedepends=(
  glibc
  gcc
  binutils
  make
  sed
  gawk
  grep
  diffutils
  texinfo
)

function build() {
  cd sed-$pkgver
  ./configure --prefix=/usr
  make
  make html
  make DESTDIR=$pkgdir install
  install -d -m755 $pkgdir/usr/share/doc/sed-$pkgver
  install -m644 doc/sed.html $pkgdir/usr/share/doc/sed-$pkgver
}
