#!/bin/bash

pkgname="systemd"
pkgver="257.3"

sources=(
	"https://github.com/systemd/systemd/archive/v$pkgver/systemd-$pkgver.tar.gz"
)

depends=(
	glibc
	libxcrypt
	util-linux
	lz4
	zstd
	bzip2
	acl
)

makedepends=(
	glibc
	gcc
	binutils
	make
	sed
	gawk
	grep
	diffutils
	meson
	ninja
	findutils
	gperf
	pkgconf
	libxcrypt
	util-linux
	lz4
	zstd
	python
	python-jinja2
	bzip2
	gettext
	acl
)

function build() {
	cd systemd-$pkgver
	sed -e 's/GROUP="render"/GROUP="video"/' \
		-e 's/GROUP="sgx", //' \
		-i rules.d/50-udev-default.rules.in
	mkdir -p build
	cd build

	meson setup .. \
		--prefix=/usr \
		--buildtype=release \
		-D default-dnssec=no \
		-D firstboot=false \
		-D install-tests=false \
		-D ldconfig=false \
		-D sysusers=false \
		-D rpmmacrosdir=no \
		-D homed=disabled \
		-D userdb=false \
		-D man=disabled \
		-D mode=release \
		-D pamconfdir=no \
		-D dev-kvm-mode=0660 \
		-D nobody-group=nogroup \
		-D sysupdate=disabled \
		-D ukify=disabled \
		-D docdir=/usr/share/doc/systemd-$pkgver
	ninja
	DESTDIR=$pkgdir ninja install
}
