#!/bin/bash

pkgname="util-linux"
pkgver="2.40.4"

sources=(
	"https://www.kernel.org/pub/linux/utils/util-linux/v$(echo -n "$pkgver" | cut -d '.' -f 1-2)/util-linux-$pkgver.tar.xz"
)

depends=(
	glibc
)

makedepends=(
	glibc
	gcc
	binutils
	make
	sed
	gawk
	grep
	diffutils
	findutils
)

function build() {
	cd util-linux-$pkgver
	./configure --bindir=/usr/bin \
		--libdir=/usr/lib \
		--runstatedir=/run \
		--sbindir=/usr/sbin \
		--disable-chfn-chsh \
		--disable-login \
		--disable-nologin \
		--disable-su \
		--disable-setpriv \
		--disable-runuser \
		--disable-pylibmount \
		--disable-liblastlog2 \
		--disable-static \
		--without-python \
		ADJTIME_PATH=/var/lib/hwclock/adjtime \
		--docdir=/usr/share/doc/util-linux-$pkgver
		make
		make DESTDIR=$pkgdir install
}
