#!/bin/bash

pkgname="zlib"
pkgver="1.3.1"

sources=(
  "https://zlib.net/fossils/zlib-$pkgver.tar.gz"
)

depends=(
  glibc
)

makedepends=(
  glibc
  gcc
  binutils
  make
  sed
  gawk
  grep
)

function build() {
  cd zlib-$pkgver
  ./configure --prefix=/usr
  make
  make DESTDIR=$pkgdir install
}
