#!/bin/bash

pkgname="diffutils"
pkgver="3.11"

sources=(
	"https://ftp.gnu.org/gnu/diffutils/diffutils-$pkgver.tar.xz"
)

depends=(
	glibc
)

USE_HOST_TOOLS=1

function build() {
	cd diffutils-$pkgver
	./configure --prefix=/usr \
		--host=x86_64-dalix-linux-gnu \
		--build=$(./build-aux/config.guess)
	make
	make DESTDIR=$pkgdir install
}
