#!/bin/bash

pkgname="gawk"
pkgver="5.3.1"

sources=(
	"https://ftp.gnu.org/gnu/gawk/gawk-$pkgver.tar.xz"
)

depends=(
	glibc
)

USE_HOST_TOOLS=1

function build() {
	cd gawk-$pkgver
	sed -i 's/extras//' Makefile.in
	./configure --prefix=/usr \
		--host=x86_64-dalix-linux-gnu \
		--build=$(build-aux/config.guess)
	make
	make DESTDIR=$pkgdir install
}
