#!/bin/bash

pkgname="gcc"
pkgver="14.2.0"
mpfrver="4.2.1"
mpcver="1.3.1"
gmpver="6.3.0"

sources=(
  "https://ftp.gnu.org/gnu/gcc/gcc-$pkgver/gcc-$pkgver.tar.xz"
  "https://ftp.gnu.org/gnu/mpfr/mpfr-$mpfrver.tar.xz"
  "https://ftp.gnu.org/gnu/mpc/mpc-$mpcver.tar.gz"
  "https://ftp.gnu.org/gnu/gmp/gmp-$gmpver.tar.xz"
)

depends=(
  glibc
  binutils
)

USE_HOST_TOOLS=1

function build() {
  cd gcc-$pkgver
  mv -v ../mpfr-$mpfrver mpfr
  mv -v ../mpc-$mpcver mpc
  mv -v ../gmp-$gmpver gmp

  case $(uname -m) in
  x86_64)
    sed -e '/m64=/s/lib64/lib/' \
      -i.orig gcc/config/i386/t-linux64
    ;;
  esac
  sed '/thread_header =/s/@.*@/gthr-posix.h/' \
    -i libgcc/Makefile.in libstdc++-v3/include/Makefile.in
  mkdir -v build
  cd build
  ../configure \
    --build=$(../config.guess) \
    --host=x86_64-dalix-linux-gnu \
    --target=x86_64-dalix-linux-gnu \
    LDFLAGS_FOR_TARGET=-L$PWD/x86_64-dalix-linux-gnu/libgcc \
    --prefix=/usr \
    --with-build-sysroot=$HOME/Opt/Cross/ \
    --enable-default-pie \
    --enable-default-ssp \
    --disable-nls \
    --disable-multilib \
    --disable-libatomic \
    --disable-libgomp \
    --disable-libquadmath \
    --disable-libsanitizer \
    --disable-libssp \
    --disable-libvtv \
    --enable-languages=c,c++
  make
  make DESTDIR=$pkgdir install
  ln -sv gcc $pkgdir/usr/bin/cc
  mkdir -p $pkgdir/usr/lib
  ln -sv /usr/bin/cpp $pkgdir/usr/lib/cpp
}
