#!/bin/bash

pkgname="patch"
pkgver="2.7.6"

sources=(
  "https://ftp.gnu.org/gnu/patch/patch-$pkgver.tar.xz"
)

depends=(
  glibc
)

USE_HOST_TOOLS=1

function build() {
  cd patch-$pkgver
  ./configure --prefix=/usr \
    --host=x86_64-dalix-linux-gnu \
    --build=$(build-aux/config.guess)
  make
  make DESTDIR=$pkgdir install
}
