#!/bin/bash

pkgname="tar"
pkgver="1.35"

sources=(
  "https://ftp.gnu.org/gnu/tar/tar-$pkgver.tar.xz"
)

depends=(
  glibc
)

USE_HOST_TOOLS=1

function build() {
  cd tar-$pkgver
  ./configure --prefix=/usr \
    --host=x86_64-dalix-linux-gnu \
    --build=$(./build-aux/config.guess)
  make
  make DESTDIR=$pkgdir install
}
