#!/bin/bash

pkgname="python"
pkgver="3.13.2"

sources=(
	"https://www.python.org/ftp/python/${pkgver}/Python-${pkgver}.tar.xz"
)

depends=(
	glibc
)

makedepends=(
	glibc
	gcc
	binutils
	make
	sed
	grep
	gawk
)

function build() {
	cd Python-$pkgver
	./configure --prefix=/usr \
		--enable-shared \
		--without-ensurepip
	make
	make DESTDIR=$pkgdir install
}
