#!/bin/bash

pkgname="util-linux"
pkgver="2.40.4"

sources=(
  "https://www.kernel.org/pub/linux/utils/util-linux/v$(echo -n "$pkgver" | grep -E -o '^[0-9]+\.[0-9]+')/util-linux-$pkgver.tar.xz"
)

depends=(
  glibc
)

makedepends=(
  glibc
  gcc
  binutils
  make
  grep
  sed
  gawk
)

function build() {
  mkdir bin
  cat <<EOF >bin/chgrp
#!/bin/bash
echo -n "Do nothing! :D" >/dev/null
EOF
  cp bin/chgrp bin/chown
  chmod +x bin/*
  export PATH="$PWD/bin:$PATH"
  cd util-linux-$pkgver
  ./configure --libdir=/usr/lib \
    --runstatedir=/run \
    --disable-chfn-chsh \
    --disable-login \
    --disable-nologin \
    --disable-su \
    --disable-setpriv \
    --disable-runuser \
    --disable-pylibmount \
    --disable-static \
    --disable-liblastlog2 \
    --without-python \
    ADJTIME_PATH=/var/lib/hwclock/adjtime \
    --docdir=/usr/share/doc/util-linux-$pkgver
  make
  make DESTDIR=$pkgdir install
}
